### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by imansayadi3** [BlockchainCommons/SmartCustody#16]
It's confusing. Unfortunately, this is exactly where my problem is solved. Is there any special software or training clip for lower level users?Or request support and implementation by reputable companies

**Comment by shannona** [comment]
This is a brand-new scenario that we're just testing out, so unfortunately no, there's no software or video at this point.

If there is anything specific that you find confusing, please let us know with an issue and we can see if we can clarify it.
