### ISSUE TITLE
Review/Feedback of Scenario-Multisig

### ISSUE THREAD

**Issue by BitcoinQnA** [BlockchainCommons/SmartCustody#8]
Hi Guys, 

Ken passed on your 'Scenario-Multisig' for review and feedback. I've just read through and think it's an excellent resource that is incredibly detailed and well structured. My feedback follows and is in chronological order with the article.

1 - SSKR is not defined or referenced [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L12). For those that might skip straight to the multisig section, I'd suggest referencing [this](https://github.com/BlockchainCommons/SmartCustody/blob/master/Docs/SSKR-Sharing.md).

2 - Typo [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L27).

3 - Suggest linking to an industrial grade [microSD card](https://www.amazon.com/SanDisk-Industrial-MicroSD-UHS-I-SDSDQAF3-016G/dp/B07CV344WJ/ref=sr_1_4?crid=LML757CAD58M&keywords=industrial+grade+micro+sd&qid=1649063312&sprefix=industrial+grade+micros%2Caps%2C186&sr=8-4) in [this](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L115) section.

4 - [Here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L388), you could make reference to verifying the entropy supplied using a tool like [Ian Coleman](https://iancoleman.io/bip39/) (offline). 

5 - Make reference to [verifying](https://docs.foundationdevices.com/firmware-update) the new Passport firmware [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L514).

6 - Spelling error "Keystone 3" [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L567).

7 - Mention [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L684) that the 'Verify Address' feature on Passport can be used to verify each subsequently generated receiving address shown by Sparrow.

8 - It's importance to stress the sensitivity of [this letter](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L712) and the impacts should it fall into the wrong hands.

9 - Passport's [PIN](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L775) should not have changed. If it has, the device is likely compromised and needs to be rotated out of the configuration.

10 - Spelling error "ordian" [here](https://github.com/BlockchainCommons/SmartCustody/blob/42089e60c543d915c0bc6c8ec34e5d50a0b71d14/Docs/Scenario-Multisig.md?plain=1#L860).

11 - Finally, I think it would be beneficial to mention the option of keeping a backup of the Sparrow Wallet export file. This is encrypted by default if the wallet is protected with a password (I'm aware your guide recommends against this). The benefit of the export file, aside from making migration to a new Sparrow instance easy, is that it also backs up all transaction labels.

**Comment by shannona** [comment]
Thanks. Great specifics for the Passport, and great comments on the rest. Everything you suggested should now be incorporated.
